import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
// Reached across packages deliberately: this is repository tooling rather than application code,
// and the point of it is that the committed set is the same drawing the api serves.
import { buildFavicons } from '../api/src/favicon/assets.js'

/**
 * Redraws the icon set committed under `web/public/favicon`.
 *
 * The api draws its own from the configured accent at boot and serves those ahead of these, and
 * the vite dev server proxies `/favicon` to it, so this set answers only where the api is not in
 * front of it: `vite preview`, or `web/dist` served by another static server. It is committed
 * rather than generated by the build because vite serves the public directory as it finds it.
 *
 * The stock accent, since a deployment's own never reaches this copy.
 * @returns {void}
 */
function writeStockFavicons(): void {
  const brand = {
    title: 'diele',
    subtitle: 'start page',
    accentLight: '#16a34a',
    accentDark: '#22c55e',
  }

  const directory = resolve(import.meta.dirname, '..', 'web', 'public', 'favicon')

  for (const [path, asset] of buildFavicons(brand)) {
    const name = path.slice(path.lastIndexOf('/') + 1)
    writeFileSync(resolve(directory, name), asset.body)
    console.log(`${name} (${asset.body.length} bytes)`)
  }
}

writeStockFavicons()
